language: python
branches:
  only:
  - master
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38
  - python: 3.8
    env: TOXENV=mypy
  - python: 3.7
    env: TOXENV=docs
install:
- pip install -U tox codecov
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  user: scrapinghub
  on:
    tags: true
    repo: scrapinghub/web-poet
    condition: "$TOXENV == py38"
  distributions: sdist bdist_wheel
  password:
    secure: I/H7Ikj1TdFyEK9kmJXfRiVL8mhKPCwMzHn1N3WGfUMyebdhIEBrZcAj6Zy530plF32Cv5u1SvToFE/YgxeXkdxlEgjyQwvmBwb0FrbS6Ra9nLINZMEtJuANcEyQy2gU2rokGKxECbM8ytUSQw0yj0bC8YKGsDzfAw4B0xGHUIjG/j8rq2b35Et6EvN6JGpiyC7UqsVGZvTbcTXbZkM2b3u1TRa/0EutYEmvWLA6ed7AqtMOl31nICSZOm+0m9VGD0rAsbAx46geSb2L+CQXWc0bNvg6P34h6sQU67s71r3hjE2vgeSquoA/TacGgB62sgbL2y/8xU/DKfypmWjUXtbSHelDcSbxn3xl1osIPv9wTwdFev032lkgVZFGR/vYqbXVvUgQc7nBpJvSP+L0hs3VT1jZti+HVLFXlu+mPSYMRcDsdXzHD0HoZoEyh1w9VdD2/GQJ6FdKxrJgS6x9ukaw5p7ZjA9IuVsIW3rTuDmbVP6WfIak9/rFYF6PfNqd34z8YHfR75mf8Z3xnKPNrNQt1PNMk7CLJWaZIrVatwExc69X2eQs0W40Epn85AmqkzLjhG+LW7mRhUqUft70l5U7rwJ4uyYYSzsyGiVYtlrwolNxxVKSU+LfMHyLA/Jscn5lopFycDiLIl2EMUpL0rdMZDfwUApRXMuWuHVIE+Q=
