language: python
branches:
  only:
  - master
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38
  - python: 3.8
    env: TOXENV=mypy
  - python: 3.7
    env: TOXENV=docs
install:
- pip install -U tox codecov
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  user: victortorres
  password:
    secure: HyeOrLjoAomYhJ3aAwBXRER2XG1UjEkftep1JeUxGNgBc8oyqY9+8ZR0ikmiI8EfWVRtgPgb4E+dM7ewMCGFg2qsU+WT6q+khQsfnrjeQkeiX0VTstG8I9uCUx1iQpAtXyaDKNVsjYH8RbZq9ZVNLuUrP/40oYKWdVYjUCMISo+M0woyF9izhV8xfBrXN7UTMJrR3oHePDHUedLLdcWQc0R3TOGIWuwTGw9EChC+DnZn2vEThJYRZ79hTM0shhLLoCQu20cDpXyWGDc7m/+Hig91TT5v3Xq2Sn143jzQAH57ahsydWxj58osJjTEt908DSROAwVN9xpzA4op9Cv2+HaGx+BtV1c/FIKrCouGnik9qLpySJlSswTWEvXohVqcoyQDv5UzDG/jmEQYvbYeBt3WEtByxJMql5uFXrZ/QXwCMALb0zJJmUJmeBthqlZtJIhZqwWmTPMVeMS/3MrOKB3ibJQaiT6h/i7xX13zB0bpiS0ibPm+ujBPUbf4qITEwtEOK/k8rbkRlzlxdzsQEPF9+VfLGaHgoJn0Z8yQqzJCuII18GyH0v4O0WJalyj2ZA7Q33t5Ez+UdBxii5WDocXB7Lcl4hUeHrJEfHLC3DRYEjfKM/Evky7ROGjeUpx27Tc3mC5dZop0RHq3Nx6h6uyXehI7Xa4oCgTjwaIG0s8=
  on:
    tags: true
    repo: scrapinghub/web-poet
    condition: "$TOXENV == py38"
  distributions: sdist bdist_wheel
