[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
show_error_codes = true
ignore_missing_imports = true
no_warn_no_return = true

[[tool.mypy.overrides]]
module = "tests.po_lib_to_return.*"
ignore_errors = true
